name: streaming_app
description: Project 1 - Streaming App for OnnoRokom Pathshala.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # for video
  chewie: ^1.3.4
  video_player: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/thumbnail/
    - assets/video_assets/
